#
# Voltus Scheduler command file generated by voltus_rail on Thu Nov 27 15:58:12 2025
#
setvar log_file ./work/voltus_extractor.log
extracted_nets VDD 
setvar output_cache_directory_name /tmp/innovus_temp_2664019_cn89.it.auth.gr_ppapadoe_46FY2j/zx_tmp_cn89.it.auth.gr_2674517
setvar library_name ./run1/era_work/incremental_output0/pgv/techonly.cl
setvar output_directory_name ./work
setvar output_file_name VDD
setvar max_error_messages 100
setvar max_resistor_length 800
setvar hierarchy_char /
layout_file /tmp/innovus_temp_2664019_cn89.it.auth.gr_ppapadoe_46FY2j/eps_out_2664019.def.gz  
setvar exec_token "/tmp/innovus_temp_2664019_cn89.it.auth.gr_ppapadoe_46FY2j/eps_out_2664019.def.gz"
setvar enable_signal_via_overhang false
setvar zx_multinet_extraction false
setvar extraction_mode early
setvar enable_zx_report_shorts true
extraction_type all none
extraction_type pattern VDD r_only
hierarchical_path_tracer netinst_table ./work/VDD.netinst
hierarchical_path_tracer cell_table ./work/VDD.cellinst
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
label port VDDvsrc1 14.0000 121.0000 Metal10
hierarchical_path_tracer pgnet_table ./work/all.pgnets
setvar output_def false
setvar cluster_via_size 25
setvar cluster_via1_maximum true
setvar def_merge_supply_shorts false
setvar promote_ports true
setvar max_cpu 1
setvar tech_file /mnt/apps/prebuilt/eda/designkits/GPDK/gsclib045/lan/flow/t1u1/reference_libs/GPDK045/gsclib045_svt_v4.4/gsclib045/qrc/qx/gpdk045.tch
setvar density_check_method database
setvar sfedb_path ./work/SFEDB 
setvar enable_binary_inst_pgdb true
setvar keep_log_file false
