#==============================================================================
# Hierarchical dofile generated by Conformal LEC
# Version: 23.10-s300 (30-Aug-2023) (64 bit executable)
#------------------------------------------------------------------------------
# Hierarchical dofile is generated by following configuration:
# write_hier_compare_dofile
#     -NOExact_pin_match
#     -Constraints
#     -INPUT_OUTPUT_Pin_equivalence
#     -BALANCED_EXTractions
#     -PREPEND_String 'report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -flowgraph -verbose'
#     -Usage
#     -Replace
#     -VERbose
#     'hier_tmp5.lec.do'
#------------------------------------------------------------------------------
# For additional reporting on 'not written' modules, see the 'VERBOSE REPORTING'
# section at the end of the hierarchical dofile
#------------------------------------------------------------------------------
# The command 'set module property' sets the instance context for the current
# root module. It is intended only for hierarchical comparison, and should
# not be modified by the user.
#------------------------------------------------------------------------------
# TERMS AND NOTATIONS USED
#------------------------------------------------------------------------------
# Module Instantiation Ratio: Average number of instantiations per matching module
# Wrapper size: Logic gates enclosing the module's instance, and bounded by key-points
# Periphery size: Logic gates in the fanin and fanout cone of instance's input and output boundary, and bounded by key-points
# 0: Indicates pin is constant zero
# 1: Indicates pin is constant one
# X: Indicates pin is full DC
# U: Indicates pin is unreachable
# Z: Indicates pin is floating
# KP<--: Indicates pin's fanin is directly connected to key-point (ignores buffers/inverters)
# -->KP: Indicates pin's fanout is directly connected to key-point (ignores buffers/inverters)
# REP: Indicates pin is representative pin
# EQ_REP: <polarity> rep_pinname>: Indicates pin is a member EQ pin with
# 'rep_pinname' specifying the representative, and 'polarity' specifying
# if it is positive or negative equivalent
# = : Indicates that the pins on LHS and RHS are mapped
# + : Indicates positive polarity for pin mapping
# - : Indicates negative polarity for pin mapping
# ? : Indicates unknown polarity for pin mapping
# G: Indicates that the pin belongs to Golden
# R: Indicates that the pin belongs to Revised
# IN: Indicates that the pin is an Input pin
# OUT: Indicates that the pin is an Output pin
# IO: Indicates that the pin is an Inout pin. Polarity of Inout pin is
#     always '?' because of name-only mapping
#==============================================================================

set_system_mode setup
vpxmode
delete set_seq_merge
set_seq_merge /wbm_cyc_o_reg  /wbm_stb_o_reg -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[1]  /picorv32_core/decoded_rs2_reg[1] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[2]  /picorv32_core/decoded_rs2_reg[2] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[3]  /picorv32_core/decoded_rs2_reg[3] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[4]  /picorv32_core/decoded_rs2_reg[4] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[11]  /picorv32_core/decoded_rs2_reg[0] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[20]  /picorv32_core/decoded_imm_j_reg[21] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[20]  /picorv32_core/decoded_imm_j_reg[22] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[20]  /picorv32_core/decoded_imm_j_reg[23] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[20]  /picorv32_core/decoded_imm_j_reg[24] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[20]  /picorv32_core/decoded_imm_j_reg[25] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[20]  /picorv32_core/decoded_imm_j_reg[26] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[20]  /picorv32_core/decoded_imm_j_reg[27] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[20]  /picorv32_core/decoded_imm_j_reg[28] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[20]  /picorv32_core/decoded_imm_j_reg[29] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[20]  /picorv32_core/decoded_imm_j_reg[30] -Golden
set_seq_merge /picorv32_core/decoded_imm_j_reg[20]  /picorv32_core/decoded_imm_j_reg[31] -Golden
set_seq_merge /picorv32_core/genblk2.pcpi_div/pcpi_ready_reg  /picorv32_core/genblk2.pcpi_div/pcpi_wr_reg -Golden
tclmode
# Root Modules
# Comparing
#-------------------------------------------------------------------------------
# MODULE picorv32_wb (G) INSTANCE / (G)
# MODULE picorv32_wb (R) INSTANCE / (R)
# Wrapper size: (G) = 0  (R) = 0
# Periphery size: (G) = 0  (R) = 0
#-------------------------------------------------------------------------------
# RESOLVED Constraints
# IN (G) wb_rst_i (REP)  =   (R) wb_rst_i (REP) (by name)
# IN (G) wb_clk_i (REP)  =   (R) wb_clk_i (REP) (by name)
# IN (G) wbm_dat_i[31] (REP)  =   (R) wbm_dat_i[31] (REP) (by name)
# IN (G) wbm_dat_i[30] (REP)  =   (R) wbm_dat_i[30] (REP) (by name)
# IN (G) wbm_dat_i[29] (REP)  =   (R) wbm_dat_i[29] (REP) (by name)
# IN (G) wbm_dat_i[28] (REP)  =   (R) wbm_dat_i[28] (REP) (by name)
# IN (G) wbm_dat_i[27] (REP)  =   (R) wbm_dat_i[27] (REP) (by name)
# IN (G) wbm_dat_i[26] (REP)  =   (R) wbm_dat_i[26] (REP) (by name)
# IN (G) wbm_dat_i[25] (REP)  =   (R) wbm_dat_i[25] (REP) (by name)
# IN (G) wbm_dat_i[24] (REP)  =   (R) wbm_dat_i[24] (REP) (by name)
# IN (G) wbm_dat_i[23] (REP)  =   (R) wbm_dat_i[23] (REP) (by name)
# IN (G) wbm_dat_i[22] (REP)  =   (R) wbm_dat_i[22] (REP) (by name)
# IN (G) wbm_dat_i[21] (REP)  =   (R) wbm_dat_i[21] (REP) (by name)
# IN (G) wbm_dat_i[20] (REP)  =   (R) wbm_dat_i[20] (REP) (by name)
# IN (G) wbm_dat_i[19] (REP)  =   (R) wbm_dat_i[19] (REP) (by name)
# IN (G) wbm_dat_i[18] (REP)  =   (R) wbm_dat_i[18] (REP) (by name)
# IN (G) wbm_dat_i[17] (REP)  =   (R) wbm_dat_i[17] (REP) (by name)
# IN (G) wbm_dat_i[16] (REP)  =   (R) wbm_dat_i[16] (REP) (by name)
# IN (G) wbm_dat_i[15] (REP)  =   (R) wbm_dat_i[15] (REP) (by name)
# IN (G) wbm_dat_i[14] (REP)  =   (R) wbm_dat_i[14] (REP) (by name)
# IN (G) wbm_dat_i[13] (REP)  =   (R) wbm_dat_i[13] (REP) (by name)
# IN (G) wbm_dat_i[12] (REP)  =   (R) wbm_dat_i[12] (REP) (by name)
# IN (G) wbm_dat_i[11] (REP)  =   (R) wbm_dat_i[11] (REP) (by name)
# IN (G) wbm_dat_i[10] (REP)  =   (R) wbm_dat_i[10] (REP) (by name)
# IN (G) wbm_dat_i[9] (REP)  =   (R) wbm_dat_i[9] (REP) (by name)
# IN (G) wbm_dat_i[8] (REP)  =   (R) wbm_dat_i[8] (REP) (by name)
# IN (G) wbm_dat_i[7] (REP)  =   (R) wbm_dat_i[7] (REP) (by name)
# IN (G) wbm_dat_i[6] (REP)  =   (R) wbm_dat_i[6] (REP) (by name)
# IN (G) wbm_dat_i[5] (REP)  =   (R) wbm_dat_i[5] (REP) (by name)
# IN (G) wbm_dat_i[4] (REP)  =   (R) wbm_dat_i[4] (REP) (by name)
# IN (G) wbm_dat_i[3] (REP)  =   (R) wbm_dat_i[3] (REP) (by name)
# IN (G) wbm_dat_i[2] (REP)  =   (R) wbm_dat_i[2] (REP) (by name)
# IN (G) wbm_dat_i[1] (REP)  =   (R) wbm_dat_i[1] (REP) (by name)
# IN (G) wbm_dat_i[0] (REP)  =   (R) wbm_dat_i[0] (REP) (by name)
# IN (G) wbm_ack_i (REP)  =   (R) wbm_ack_i (REP) (by name)
# IN (G) pcpi_wr (REP)  =   (R) pcpi_wr (REP) (by name)
# IN (G) pcpi_rd[31] (REP)  =   (R) pcpi_rd[31] (REP) (by name)
# IN (G) pcpi_rd[30] (REP)  =   (R) pcpi_rd[30] (REP) (by name)
# IN (G) pcpi_rd[29] (REP)  =   (R) pcpi_rd[29] (REP) (by name)
# IN (G) pcpi_rd[28] (REP)  =   (R) pcpi_rd[28] (REP) (by name)
# IN (G) pcpi_rd[27] (REP)  =   (R) pcpi_rd[27] (REP) (by name)
# IN (G) pcpi_rd[26] (REP)  =   (R) pcpi_rd[26] (REP) (by name)
# IN (G) pcpi_rd[25] (REP)  =   (R) pcpi_rd[25] (REP) (by name)
# IN (G) pcpi_rd[24] (REP)  =   (R) pcpi_rd[24] (REP) (by name)
# IN (G) pcpi_rd[23] (REP)  =   (R) pcpi_rd[23] (REP) (by name)
# IN (G) pcpi_rd[22] (REP)  =   (R) pcpi_rd[22] (REP) (by name)
# IN (G) pcpi_rd[21] (REP)  =   (R) pcpi_rd[21] (REP) (by name)
# IN (G) pcpi_rd[20] (REP)  =   (R) pcpi_rd[20] (REP) (by name)
# IN (G) pcpi_rd[19] (REP)  =   (R) pcpi_rd[19] (REP) (by name)
# IN (G) pcpi_rd[18] (REP)  =   (R) pcpi_rd[18] (REP) (by name)
# IN (G) pcpi_rd[17] (REP)  =   (R) pcpi_rd[17] (REP) (by name)
# IN (G) pcpi_rd[16] (REP)  =   (R) pcpi_rd[16] (REP) (by name)
# IN (G) pcpi_rd[15] (REP)  =   (R) pcpi_rd[15] (REP) (by name)
# IN (G) pcpi_rd[14] (REP)  =   (R) pcpi_rd[14] (REP) (by name)
# IN (G) pcpi_rd[13] (REP)  =   (R) pcpi_rd[13] (REP) (by name)
# IN (G) pcpi_rd[12] (REP)  =   (R) pcpi_rd[12] (REP) (by name)
# IN (G) pcpi_rd[11] (REP)  =   (R) pcpi_rd[11] (REP) (by name)
# IN (G) pcpi_rd[10] (REP)  =   (R) pcpi_rd[10] (REP) (by name)
# IN (G) pcpi_rd[9] (REP)  =   (R) pcpi_rd[9] (REP) (by name)
# IN (G) pcpi_rd[8] (REP)  =   (R) pcpi_rd[8] (REP) (by name)
# IN (G) pcpi_rd[7] (REP)  =   (R) pcpi_rd[7] (REP) (by name)
# IN (G) pcpi_rd[6] (REP)  =   (R) pcpi_rd[6] (REP) (by name)
# IN (G) pcpi_rd[5] (REP)  =   (R) pcpi_rd[5] (REP) (by name)
# IN (G) pcpi_rd[4] (REP)  =   (R) pcpi_rd[4] (REP) (by name)
# IN (G) pcpi_rd[3] (REP)  =   (R) pcpi_rd[3] (REP) (by name)
# IN (G) pcpi_rd[2] (REP)  =   (R) pcpi_rd[2] (REP) (by name)
# IN (G) pcpi_rd[1] (REP)  =   (R) pcpi_rd[1] (REP) (by name)
# IN (G) pcpi_rd[0] (REP)  =   (R) pcpi_rd[0] (REP) (by name)
# IN (G) pcpi_wait (REP)  =   (R) pcpi_wait (REP) (by name)
# IN (G) pcpi_ready (REP)  =   (R) pcpi_ready (REP) (by name)
# IN (G) irq[31] (REP)  =   (R) irq[31] (REP) (by name)
# IN (G) irq[30] (REP)  =   (R) irq[30] (REP) (by name)
# IN (G) irq[29] (REP)  =   (R) irq[29] (REP) (by name)
# IN (G) irq[28] (REP)  =   (R) irq[28] (REP) (by name)
# IN (G) irq[27] (REP)  =   (R) irq[27] (REP) (by name)
# IN (G) irq[26] (REP)  =   (R) irq[26] (REP) (by name)
# IN (G) irq[25] (REP)  =   (R) irq[25] (REP) (by name)
# IN (G) irq[24] (REP)  =   (R) irq[24] (REP) (by name)
# IN (G) irq[23] (REP)  =   (R) irq[23] (REP) (by name)
# IN (G) irq[22] (REP)  =   (R) irq[22] (REP) (by name)
# IN (G) irq[21] (REP)  =   (R) irq[21] (REP) (by name)
# IN (G) irq[20] (REP)  =   (R) irq[20] (REP) (by name)
# IN (G) irq[19] (REP)  =   (R) irq[19] (REP) (by name)
# IN (G) irq[18] (REP)  =   (R) irq[18] (REP) (by name)
# IN (G) irq[17] (REP)  =   (R) irq[17] (REP) (by name)
# IN (G) irq[16] (REP)  =   (R) irq[16] (REP) (by name)
# IN (G) irq[15] (REP)  =   (R) irq[15] (REP) (by name)
# IN (G) irq[14] (REP)  =   (R) irq[14] (REP) (by name)
# IN (G) irq[13] (REP)  =   (R) irq[13] (REP) (by name)
# IN (G) irq[12] (REP)  =   (R) irq[12] (REP) (by name)
# IN (G) irq[11] (REP)  =   (R) irq[11] (REP) (by name)
# IN (G) irq[10] (REP)  =   (R) irq[10] (REP) (by name)
# IN (G) irq[9] (REP)  =   (R) irq[9] (REP) (by name)
# IN (G) irq[8] (REP)  =   (R) irq[8] (REP) (by name)
# IN (G) irq[7] (REP)  =   (R) irq[7] (REP) (by name)
# IN (G) irq[6] (REP)  =   (R) irq[6] (REP) (by name)
# IN (G) irq[5] (REP)  =   (R) irq[5] (REP) (by name)
# IN (G) irq[4] (REP)  =   (R) irq[4] (REP) (by name)
# IN (G) irq[3] (REP)  =   (R) irq[3] (REP) (by name)
# IN (G) irq[2] (REP)  =   (R) irq[2] (REP) (by name)
# IN (G) irq[1] (REP)  =   (R) irq[1] (REP) (by name)
# IN (G) irq[0] (REP)  =   (R) irq[0] (REP) (by name)
# RESOLVED Constraints
# OUT (G) trap (REP)  =   (R) trap (REP) (by name)
# OUT (G) wbm_adr_o[31] (REP)  =   (R) wbm_adr_o[31] (REP) (by name)
# OUT (G) wbm_adr_o[30] (REP)  =   (R) wbm_adr_o[30] (REP) (by name)
# OUT (G) wbm_adr_o[29] (REP)  =   (R) wbm_adr_o[29] (REP) (by name)
# OUT (G) wbm_adr_o[28] (REP)  =   (R) wbm_adr_o[28] (REP) (by name)
# OUT (G) wbm_adr_o[27] (REP)  =   (R) wbm_adr_o[27] (REP) (by name)
# OUT (G) wbm_adr_o[26] (REP)  =   (R) wbm_adr_o[26] (REP) (by name)
# OUT (G) wbm_adr_o[25] (REP)  =   (R) wbm_adr_o[25] (REP) (by name)
# OUT (G) wbm_adr_o[24] (REP)  =   (R) wbm_adr_o[24] (REP) (by name)
# OUT (G) wbm_adr_o[23] (REP)  =   (R) wbm_adr_o[23] (REP) (by name)
# OUT (G) wbm_adr_o[22] (REP)  =   (R) wbm_adr_o[22] (REP) (by name)
# OUT (G) wbm_adr_o[21] (REP)  =   (R) wbm_adr_o[21] (REP) (by name)
# OUT (G) wbm_adr_o[20] (REP)  =   (R) wbm_adr_o[20] (REP) (by name)
# OUT (G) wbm_adr_o[19] (REP)  =   (R) wbm_adr_o[19] (REP) (by name)
# OUT (G) wbm_adr_o[18] (REP)  =   (R) wbm_adr_o[18] (REP) (by name)
# OUT (G) wbm_adr_o[17] (REP)  =   (R) wbm_adr_o[17] (REP) (by name)
# OUT (G) wbm_adr_o[16] (REP)  =   (R) wbm_adr_o[16] (REP) (by name)
# OUT (G) wbm_adr_o[15] (REP)  =   (R) wbm_adr_o[15] (REP) (by name)
# OUT (G) wbm_adr_o[14] (REP)  =   (R) wbm_adr_o[14] (REP) (by name)
# OUT (G) wbm_adr_o[13] (REP)  =   (R) wbm_adr_o[13] (REP) (by name)
# OUT (G) wbm_adr_o[12] (REP)  =   (R) wbm_adr_o[12] (REP) (by name)
# OUT (G) wbm_adr_o[11] (REP)  =   (R) wbm_adr_o[11] (REP) (by name)
# OUT (G) wbm_adr_o[10] (REP)  =   (R) wbm_adr_o[10] (REP) (by name)
# OUT (G) wbm_adr_o[9] (REP)  =   (R) wbm_adr_o[9] (REP) (by name)
# OUT (G) wbm_adr_o[8] (REP)  =   (R) wbm_adr_o[8] (REP) (by name)
# OUT (G) wbm_adr_o[7] (REP)  =   (R) wbm_adr_o[7] (REP) (by name)
# OUT (G) wbm_adr_o[6] (REP)  =   (R) wbm_adr_o[6] (REP) (by name)
# OUT (G) wbm_adr_o[5] (REP)  =   (R) wbm_adr_o[5] (REP) (by name)
# OUT (G) wbm_adr_o[4] (REP)  =   (R) wbm_adr_o[4] (REP) (by name)
# OUT (G) wbm_adr_o[3] (REP)  =   (R) wbm_adr_o[3] (REP) (by name)
# OUT (G) wbm_adr_o[2] (REP)  =   (R) wbm_adr_o[2] (REP) (by name)
# OUT (G) wbm_adr_o[1] 0(REP)  =   (R) wbm_adr_o[1] 0(REP) (by name)
# OUT (G) wbm_adr_o[0] 0(REP)  =   (R) wbm_adr_o[0] 0(REP) (by name)
# OUT (G) wbm_dat_o[31] (REP)  =   (R) wbm_dat_o[31] (REP) (by name)
# OUT (G) wbm_dat_o[30] (REP)  =   (R) wbm_dat_o[30] (REP) (by name)
# OUT (G) wbm_dat_o[29] (REP)  =   (R) wbm_dat_o[29] (REP) (by name)
# OUT (G) wbm_dat_o[28] (REP)  =   (R) wbm_dat_o[28] (REP) (by name)
# OUT (G) wbm_dat_o[27] (REP)  =   (R) wbm_dat_o[27] (REP) (by name)
# OUT (G) wbm_dat_o[26] (REP)  =   (R) wbm_dat_o[26] (REP) (by name)
# OUT (G) wbm_dat_o[25] (REP)  =   (R) wbm_dat_o[25] (REP) (by name)
# OUT (G) wbm_dat_o[24] (REP)  =   (R) wbm_dat_o[24] (REP) (by name)
# OUT (G) wbm_dat_o[23] (REP)  =   (R) wbm_dat_o[23] (REP) (by name)
# OUT (G) wbm_dat_o[22] (REP)  =   (R) wbm_dat_o[22] (REP) (by name)
# OUT (G) wbm_dat_o[21] (REP)  =   (R) wbm_dat_o[21] (REP) (by name)
# OUT (G) wbm_dat_o[20] (REP)  =   (R) wbm_dat_o[20] (REP) (by name)
# OUT (G) wbm_dat_o[19] (REP)  =   (R) wbm_dat_o[19] (REP) (by name)
# OUT (G) wbm_dat_o[18] (REP)  =   (R) wbm_dat_o[18] (REP) (by name)
# OUT (G) wbm_dat_o[17] (REP)  =   (R) wbm_dat_o[17] (REP) (by name)
# OUT (G) wbm_dat_o[16] (REP)  =   (R) wbm_dat_o[16] (REP) (by name)
# OUT (G) wbm_dat_o[15] (REP)  =   (R) wbm_dat_o[15] (REP) (by name)
# OUT (G) wbm_dat_o[14] (REP)  =   (R) wbm_dat_o[14] (REP) (by name)
# OUT (G) wbm_dat_o[13] (REP)  =   (R) wbm_dat_o[13] (REP) (by name)
# OUT (G) wbm_dat_o[12] (REP)  =   (R) wbm_dat_o[12] (REP) (by name)
# OUT (G) wbm_dat_o[11] (REP)  =   (R) wbm_dat_o[11] (REP) (by name)
# OUT (G) wbm_dat_o[10] (REP)  =   (R) wbm_dat_o[10] (REP) (by name)
# OUT (G) wbm_dat_o[9] (REP)  =   (R) wbm_dat_o[9] (REP) (by name)
# OUT (G) wbm_dat_o[8] (REP)  =   (R) wbm_dat_o[8] (REP) (by name)
# OUT (G) wbm_dat_o[7] (REP)  =   (R) wbm_dat_o[7] (REP) (by name)
# OUT (G) wbm_dat_o[6] (REP)  =   (R) wbm_dat_o[6] (REP) (by name)
# OUT (G) wbm_dat_o[5] (REP)  =   (R) wbm_dat_o[5] (REP) (by name)
# OUT (G) wbm_dat_o[4] (REP)  =   (R) wbm_dat_o[4] (REP) (by name)
# OUT (G) wbm_dat_o[3] (REP)  =   (R) wbm_dat_o[3] (REP) (by name)
# OUT (G) wbm_dat_o[2] (REP)  =   (R) wbm_dat_o[2] (REP) (by name)
# OUT (G) wbm_dat_o[1] (REP)  =   (R) wbm_dat_o[1] (REP) (by name)
# OUT (G) wbm_dat_o[0] (REP)  =   (R) wbm_dat_o[0] (REP) (by name)
# OUT (G) wbm_we_o (REP)  =   (R) wbm_we_o (REP) (by name)
# OUT (G) wbm_sel_o[3] (REP)  =   (R) wbm_sel_o[3] (REP) (by name)
# OUT (G) wbm_sel_o[2] (REP)  =   (R) wbm_sel_o[2] (REP) (by name)
# OUT (G) wbm_sel_o[1] (REP)  =   (R) wbm_sel_o[1] (REP) (by name)
# OUT (G) wbm_sel_o[0] (REP)  =   (R) wbm_sel_o[0] (REP) (by name)
# OUT (G) wbm_stb_o (REP)  =   (R) wbm_stb_o (REP) (by name)
# OUT (G) wbm_cyc_o  (EQ_REP: +wbm_stb_o)  =   (R) wbm_cyc_o  (EQ_REP: +wbm_stb_o) (by name)
# OUT (G) pcpi_valid (REP)  =   (R) pcpi_valid (REP) (by name)
# OUT (G) pcpi_insn[31] (REP)  =   (R) pcpi_insn[31] (REP) (by name)
# OUT (G) pcpi_insn[30] (REP)  =   (R) pcpi_insn[30] (REP) (by name)
# OUT (G) pcpi_insn[29] (REP)  =   (R) pcpi_insn[29] (REP) (by name)
# OUT (G) pcpi_insn[28] (REP)  =   (R) pcpi_insn[28] (REP) (by name)
# OUT (G) pcpi_insn[27] (REP)  =   (R) pcpi_insn[27] (REP) (by name)
# OUT (G) pcpi_insn[26] (REP)  =   (R) pcpi_insn[26] (REP) (by name)
# OUT (G) pcpi_insn[25] (REP)  =   (R) pcpi_insn[25] (REP) (by name)
# OUT (G) pcpi_insn[24] (REP)  =   (R) pcpi_insn[24] (REP) (by name)
# OUT (G) pcpi_insn[23] (REP)  =   (R) pcpi_insn[23] (REP) (by name)
# OUT (G) pcpi_insn[22] (REP)  =   (R) pcpi_insn[22] (REP) (by name)
# OUT (G) pcpi_insn[21] (REP)  =   (R) pcpi_insn[21] (REP) (by name)
# OUT (G) pcpi_insn[20] (REP)  =   (R) pcpi_insn[20] (REP) (by name)
# OUT (G) pcpi_insn[19] (REP)  =   (R) pcpi_insn[19] (REP) (by name)
# OUT (G) pcpi_insn[18] (REP)  =   (R) pcpi_insn[18] (REP) (by name)
# OUT (G) pcpi_insn[17] (REP)  =   (R) pcpi_insn[17] (REP) (by name)
# OUT (G) pcpi_insn[16] (REP)  =   (R) pcpi_insn[16] (REP) (by name)
# OUT (G) pcpi_insn[15] (REP)  =   (R) pcpi_insn[15] (REP) (by name)
# OUT (G) pcpi_insn[14] (REP)  =   (R) pcpi_insn[14] (REP) (by name)
# OUT (G) pcpi_insn[13] (REP)  =   (R) pcpi_insn[13] (REP) (by name)
# OUT (G) pcpi_insn[12] (REP)  =   (R) pcpi_insn[12] (REP) (by name)
# OUT (G) pcpi_insn[11] (REP)  =   (R) pcpi_insn[11] (REP) (by name)
# OUT (G) pcpi_insn[10] (REP)  =   (R) pcpi_insn[10] (REP) (by name)
# OUT (G) pcpi_insn[9] (REP)  =   (R) pcpi_insn[9] (REP) (by name)
# OUT (G) pcpi_insn[8] (REP)  =   (R) pcpi_insn[8] (REP) (by name)
# OUT (G) pcpi_insn[7] (REP)  =   (R) pcpi_insn[7] (REP) (by name)
# OUT (G) pcpi_insn[6] (REP)  =   (R) pcpi_insn[6] (REP) (by name)
# OUT (G) pcpi_insn[5] (REP)  =   (R) pcpi_insn[5] (REP) (by name)
# OUT (G) pcpi_insn[4] (REP)  =   (R) pcpi_insn[4] (REP) (by name)
# OUT (G) pcpi_insn[3] (REP)  =   (R) pcpi_insn[3] (REP) (by name)
# OUT (G) pcpi_insn[2] (REP)  =   (R) pcpi_insn[2] (REP) (by name)
# OUT (G) pcpi_insn[1] (REP)  =   (R) pcpi_insn[1] (REP) (by name)
# OUT (G) pcpi_insn[0] (REP)  =   (R) pcpi_insn[0] (REP) (by name)
# OUT (G) pcpi_rs1[31] (REP)  =   (R) pcpi_rs1[31] (REP) (by name)
# OUT (G) pcpi_rs1[30] (REP)  =   (R) pcpi_rs1[30] (REP) (by name)
# OUT (G) pcpi_rs1[29] (REP)  =   (R) pcpi_rs1[29] (REP) (by name)
# OUT (G) pcpi_rs1[28] (REP)  =   (R) pcpi_rs1[28] (REP) (by name)
# OUT (G) pcpi_rs1[27] (REP)  =   (R) pcpi_rs1[27] (REP) (by name)
# OUT (G) pcpi_rs1[26] (REP)  =   (R) pcpi_rs1[26] (REP) (by name)
# OUT (G) pcpi_rs1[25] (REP)  =   (R) pcpi_rs1[25] (REP) (by name)
# OUT (G) pcpi_rs1[24] (REP)  =   (R) pcpi_rs1[24] (REP) (by name)
# OUT (G) pcpi_rs1[23] (REP)  =   (R) pcpi_rs1[23] (REP) (by name)
# OUT (G) pcpi_rs1[22] (REP)  =   (R) pcpi_rs1[22] (REP) (by name)
# OUT (G) pcpi_rs1[21] (REP)  =   (R) pcpi_rs1[21] (REP) (by name)
# OUT (G) pcpi_rs1[20] (REP)  =   (R) pcpi_rs1[20] (REP) (by name)
# OUT (G) pcpi_rs1[19] (REP)  =   (R) pcpi_rs1[19] (REP) (by name)
# OUT (G) pcpi_rs1[18] (REP)  =   (R) pcpi_rs1[18] (REP) (by name)
# OUT (G) pcpi_rs1[17] (REP)  =   (R) pcpi_rs1[17] (REP) (by name)
# OUT (G) pcpi_rs1[16] (REP)  =   (R) pcpi_rs1[16] (REP) (by name)
# OUT (G) pcpi_rs1[15] (REP)  =   (R) pcpi_rs1[15] (REP) (by name)
# OUT (G) pcpi_rs1[14] (REP)  =   (R) pcpi_rs1[14] (REP) (by name)
# OUT (G) pcpi_rs1[13] (REP)  =   (R) pcpi_rs1[13] (REP) (by name)
# OUT (G) pcpi_rs1[12] (REP)  =   (R) pcpi_rs1[12] (REP) (by name)
# OUT (G) pcpi_rs1[11] (REP)  =   (R) pcpi_rs1[11] (REP) (by name)
# OUT (G) pcpi_rs1[10] (REP)  =   (R) pcpi_rs1[10] (REP) (by name)
# OUT (G) pcpi_rs1[9] (REP)  =   (R) pcpi_rs1[9] (REP) (by name)
# OUT (G) pcpi_rs1[8] (REP)  =   (R) pcpi_rs1[8] (REP) (by name)
# OUT (G) pcpi_rs1[7] (REP)  =   (R) pcpi_rs1[7] (REP) (by name)
# OUT (G) pcpi_rs1[6] (REP)  =   (R) pcpi_rs1[6] (REP) (by name)
# OUT (G) pcpi_rs1[5] (REP)  =   (R) pcpi_rs1[5] (REP) (by name)
# OUT (G) pcpi_rs1[4] (REP)  =   (R) pcpi_rs1[4] (REP) (by name)
# OUT (G) pcpi_rs1[3] (REP)  =   (R) pcpi_rs1[3] (REP) (by name)
# OUT (G) pcpi_rs1[2] (REP)  =   (R) pcpi_rs1[2] (REP) (by name)
# OUT (G) pcpi_rs1[1] (REP)  =   (R) pcpi_rs1[1] (REP) (by name)
# OUT (G) pcpi_rs1[0] (REP)  =   (R) pcpi_rs1[0] (REP) (by name)
# OUT (G) pcpi_rs2[31] (REP)  =   (R) pcpi_rs2[31] (REP) (by name)
# OUT (G) pcpi_rs2[30] (REP)  =   (R) pcpi_rs2[30] (REP) (by name)
# OUT (G) pcpi_rs2[29] (REP)  =   (R) pcpi_rs2[29] (REP) (by name)
# OUT (G) pcpi_rs2[28] (REP)  =   (R) pcpi_rs2[28] (REP) (by name)
# OUT (G) pcpi_rs2[27] (REP)  =   (R) pcpi_rs2[27] (REP) (by name)
# OUT (G) pcpi_rs2[26] (REP)  =   (R) pcpi_rs2[26] (REP) (by name)
# OUT (G) pcpi_rs2[25] (REP)  =   (R) pcpi_rs2[25] (REP) (by name)
# OUT (G) pcpi_rs2[24] (REP)  =   (R) pcpi_rs2[24] (REP) (by name)
# OUT (G) pcpi_rs2[23] (REP)  =   (R) pcpi_rs2[23] (REP) (by name)
# OUT (G) pcpi_rs2[22] (REP)  =   (R) pcpi_rs2[22] (REP) (by name)
# OUT (G) pcpi_rs2[21] (REP)  =   (R) pcpi_rs2[21] (REP) (by name)
# OUT (G) pcpi_rs2[20] (REP)  =   (R) pcpi_rs2[20] (REP) (by name)
# OUT (G) pcpi_rs2[19] (REP)  =   (R) pcpi_rs2[19] (REP) (by name)
# OUT (G) pcpi_rs2[18] (REP)  =   (R) pcpi_rs2[18] (REP) (by name)
# OUT (G) pcpi_rs2[17] (REP)  =   (R) pcpi_rs2[17] (REP) (by name)
# OUT (G) pcpi_rs2[16] (REP)  =   (R) pcpi_rs2[16] (REP) (by name)
# OUT (G) pcpi_rs2[15] (REP)  =   (R) pcpi_rs2[15] (REP) (by name)
# OUT (G) pcpi_rs2[14] (REP)  =   (R) pcpi_rs2[14] (REP) (by name)
# OUT (G) pcpi_rs2[13] (REP)  =   (R) pcpi_rs2[13] (REP) (by name)
# OUT (G) pcpi_rs2[12] (REP)  =   (R) pcpi_rs2[12] (REP) (by name)
# OUT (G) pcpi_rs2[11] (REP)  =   (R) pcpi_rs2[11] (REP) (by name)
# OUT (G) pcpi_rs2[10] (REP)  =   (R) pcpi_rs2[10] (REP) (by name)
# OUT (G) pcpi_rs2[9] (REP)  =   (R) pcpi_rs2[9] (REP) (by name)
# OUT (G) pcpi_rs2[8] (REP)  =   (R) pcpi_rs2[8] (REP) (by name)
# OUT (G) pcpi_rs2[7] (REP)  =   (R) pcpi_rs2[7] (REP) (by name)
# OUT (G) pcpi_rs2[6] (REP)  =   (R) pcpi_rs2[6] (REP) (by name)
# OUT (G) pcpi_rs2[5] (REP)  =   (R) pcpi_rs2[5] (REP) (by name)
# OUT (G) pcpi_rs2[4] (REP)  =   (R) pcpi_rs2[4] (REP) (by name)
# OUT (G) pcpi_rs2[3] (REP)  =   (R) pcpi_rs2[3] (REP) (by name)
# OUT (G) pcpi_rs2[2] (REP)  =   (R) pcpi_rs2[2] (REP) (by name)
# OUT (G) pcpi_rs2[1] (REP)  =   (R) pcpi_rs2[1] (REP) (by name)
# OUT (G) pcpi_rs2[0] (REP)  =   (R) pcpi_rs2[0] (REP) (by name)
# OUT (G) eoi[31] (REP)  =   (R) eoi[31] (REP) (by name)
# OUT (G) eoi[30] (REP)  =   (R) eoi[30] (REP) (by name)
# OUT (G) eoi[29] (REP)  =   (R) eoi[29] (REP) (by name)
# OUT (G) eoi[28] (REP)  =   (R) eoi[28] (REP) (by name)
# OUT (G) eoi[27] (REP)  =   (R) eoi[27] (REP) (by name)
# OUT (G) eoi[26] (REP)  =   (R) eoi[26] (REP) (by name)
# OUT (G) eoi[25] (REP)  =   (R) eoi[25] (REP) (by name)
# OUT (G) eoi[24] (REP)  =   (R) eoi[24] (REP) (by name)
# OUT (G) eoi[23] (REP)  =   (R) eoi[23] (REP) (by name)
# OUT (G) eoi[22] (REP)  =   (R) eoi[22] (REP) (by name)
# OUT (G) eoi[21] (REP)  =   (R) eoi[21] (REP) (by name)
# OUT (G) eoi[20] (REP)  =   (R) eoi[20] (REP) (by name)
# OUT (G) eoi[19] (REP)  =   (R) eoi[19] (REP) (by name)
# OUT (G) eoi[18] (REP)  =   (R) eoi[18] (REP) (by name)
# OUT (G) eoi[17] (REP)  =   (R) eoi[17] (REP) (by name)
# OUT (G) eoi[16] (REP)  =   (R) eoi[16] (REP) (by name)
# OUT (G) eoi[15] (REP)  =   (R) eoi[15] (REP) (by name)
# OUT (G) eoi[14] (REP)  =   (R) eoi[14] (REP) (by name)
# OUT (G) eoi[13] (REP)  =   (R) eoi[13] (REP) (by name)
# OUT (G) eoi[12] (REP)  =   (R) eoi[12] (REP) (by name)
# OUT (G) eoi[11] (REP)  =   (R) eoi[11] (REP) (by name)
# OUT (G) eoi[10] (REP)  =   (R) eoi[10] (REP) (by name)
# OUT (G) eoi[9] (REP)  =   (R) eoi[9] (REP) (by name)
# OUT (G) eoi[8] (REP)  =   (R) eoi[8] (REP) (by name)
# OUT (G) eoi[7] (REP)  =   (R) eoi[7] (REP) (by name)
# OUT (G) eoi[6] (REP)  =   (R) eoi[6] (REP) (by name)
# OUT (G) eoi[5] (REP)  =   (R) eoi[5] (REP) (by name)
# OUT (G) eoi[4] (REP)  =   (R) eoi[4] (REP) (by name)
# OUT (G) eoi[3] (REP)  =   (R) eoi[3] (REP) (by name)
# OUT (G) eoi[2] (REP)  =   (R) eoi[2] (REP) (by name)
# OUT (G) eoi[1] (REP)  =   (R) eoi[1] (REP) (by name)
# OUT (G) eoi[0] (REP)  =   (R) eoi[0] (REP) (by name)
# OUT (G) trace_valid 0(REP)  =   (R) trace_valid 0(REP) (by name)
# OUT (G) trace_data[35] 0(REP)  =   (R) trace_data[35] 0(REP) (by name)
# OUT (G) trace_data[34] 0(REP)  =   (R) trace_data[34] 0(REP) (by name)
# OUT (G) trace_data[33] 0(REP)  =   (R) trace_data[33] 0(REP) (by name)
# OUT (G) trace_data[32] 0(REP)  =   (R) trace_data[32] 0(REP) (by name)
# OUT (G) trace_data[31] 0(REP)  =   (R) trace_data[31] 0(REP) (by name)
# OUT (G) trace_data[30] 0(REP)  =   (R) trace_data[30] 0(REP) (by name)
# OUT (G) trace_data[29] 0(REP)  =   (R) trace_data[29] 0(REP) (by name)
# OUT (G) trace_data[28] 0(REP)  =   (R) trace_data[28] 0(REP) (by name)
# OUT (G) trace_data[27] 0(REP)  =   (R) trace_data[27] 0(REP) (by name)
# OUT (G) trace_data[26] 0(REP)  =   (R) trace_data[26] 0(REP) (by name)
# OUT (G) trace_data[25] 0(REP)  =   (R) trace_data[25] 0(REP) (by name)
# OUT (G) trace_data[24] 0(REP)  =   (R) trace_data[24] 0(REP) (by name)
# OUT (G) trace_data[23] 0(REP)  =   (R) trace_data[23] 0(REP) (by name)
# OUT (G) trace_data[22] 0(REP)  =   (R) trace_data[22] 0(REP) (by name)
# OUT (G) trace_data[21] 0(REP)  =   (R) trace_data[21] 0(REP) (by name)
# OUT (G) trace_data[20] 0(REP)  =   (R) trace_data[20] 0(REP) (by name)
# OUT (G) trace_data[19] 0(REP)  =   (R) trace_data[19] 0(REP) (by name)
# OUT (G) trace_data[18] 0(REP)  =   (R) trace_data[18] 0(REP) (by name)
# OUT (G) trace_data[17] 0(REP)  =   (R) trace_data[17] 0(REP) (by name)
# OUT (G) trace_data[16] 0(REP)  =   (R) trace_data[16] 0(REP) (by name)
# OUT (G) trace_data[15] 0(REP)  =   (R) trace_data[15] 0(REP) (by name)
# OUT (G) trace_data[14] 0(REP)  =   (R) trace_data[14] 0(REP) (by name)
# OUT (G) trace_data[13] 0(REP)  =   (R) trace_data[13] 0(REP) (by name)
# OUT (G) trace_data[12] 0(REP)  =   (R) trace_data[12] 0(REP) (by name)
# OUT (G) trace_data[11] 0(REP)  =   (R) trace_data[11] 0(REP) (by name)
# OUT (G) trace_data[10] 0(REP)  =   (R) trace_data[10] 0(REP) (by name)
# OUT (G) trace_data[9] 0(REP)  =   (R) trace_data[9] 0(REP) (by name)
# OUT (G) trace_data[8] 0(REP)  =   (R) trace_data[8] 0(REP) (by name)
# OUT (G) trace_data[7] 0(REP)  =   (R) trace_data[7] 0(REP) (by name)
# OUT (G) trace_data[6] 0(REP)  =   (R) trace_data[6] 0(REP) (by name)
# OUT (G) trace_data[5] 0(REP)  =   (R) trace_data[5] 0(REP) (by name)
# OUT (G) trace_data[4] 0(REP)  =   (R) trace_data[4] 0(REP) (by name)
# OUT (G) trace_data[3] 0(REP)  =   (R) trace_data[3] 0(REP) (by name)
# OUT (G) trace_data[2] 0(REP)  =   (R) trace_data[2] 0(REP) (by name)
# OUT (G) trace_data[1] 0(REP)  =   (R) trace_data[1] 0(REP) (by name)
# OUT (G) trace_data[0] 0(REP)  =   (R) trace_data[0] 0(REP) (by name)
# OUT (G) mem_instr (REP)  =   (R) mem_instr (REP) (by name)
set_root_module picorv32_wb -Golden
set_root_module picorv32_wb -Revised
set_module_property -instance / -Golden
set_module_property -instance / -Revised
# Constraint commands 
add_output_stuck_at 0 {wbm_adr_o[1]} -Golden -hier
add_output_stuck_at 0 {wbm_adr_o[0]} -Golden -hier
#add_output_equivalences wbm_stb_o wbm_cyc_o -hier -Golden
#add_ignored_outputs wbm_cyc_o -Golden -System
# (EQ)
add_output_stuck_at 0 trace_valid -Golden -hier
add_output_stuck_at 0 {trace_data[35]} -Golden -hier
add_output_stuck_at 0 {trace_data[34]} -Golden -hier
add_output_stuck_at 0 {trace_data[33]} -Golden -hier
add_output_stuck_at 0 {trace_data[32]} -Golden -hier
add_output_stuck_at 0 {trace_data[31]} -Golden -hier
add_output_stuck_at 0 {trace_data[30]} -Golden -hier
add_output_stuck_at 0 {trace_data[29]} -Golden -hier
add_output_stuck_at 0 {trace_data[28]} -Golden -hier
add_output_stuck_at 0 {trace_data[27]} -Golden -hier
add_output_stuck_at 0 {trace_data[26]} -Golden -hier
add_output_stuck_at 0 {trace_data[25]} -Golden -hier
add_output_stuck_at 0 {trace_data[24]} -Golden -hier
add_output_stuck_at 0 {trace_data[23]} -Golden -hier
add_output_stuck_at 0 {trace_data[22]} -Golden -hier
add_output_stuck_at 0 {trace_data[21]} -Golden -hier
add_output_stuck_at 0 {trace_data[20]} -Golden -hier
add_output_stuck_at 0 {trace_data[19]} -Golden -hier
add_output_stuck_at 0 {trace_data[18]} -Golden -hier
add_output_stuck_at 0 {trace_data[17]} -Golden -hier
add_output_stuck_at 0 {trace_data[16]} -Golden -hier
add_output_stuck_at 0 {trace_data[15]} -Golden -hier
add_output_stuck_at 0 {trace_data[14]} -Golden -hier
add_output_stuck_at 0 {trace_data[13]} -Golden -hier
add_output_stuck_at 0 {trace_data[12]} -Golden -hier
add_output_stuck_at 0 {trace_data[11]} -Golden -hier
add_output_stuck_at 0 {trace_data[10]} -Golden -hier
add_output_stuck_at 0 {trace_data[9]} -Golden -hier
add_output_stuck_at 0 {trace_data[8]} -Golden -hier
add_output_stuck_at 0 {trace_data[7]} -Golden -hier
add_output_stuck_at 0 {trace_data[6]} -Golden -hier
add_output_stuck_at 0 {trace_data[5]} -Golden -hier
add_output_stuck_at 0 {trace_data[4]} -Golden -hier
add_output_stuck_at 0 {trace_data[3]} -Golden -hier
add_output_stuck_at 0 {trace_data[2]} -Golden -hier
add_output_stuck_at 0 {trace_data[1]} -Golden -hier
add_output_stuck_at 0 {trace_data[0]} -Golden -hier
add_output_stuck_at 0 {wbm_adr_o[1]} -Revised -hier
add_output_stuck_at 0 {wbm_adr_o[0]} -Revised -hier
#add_output_equivalences wbm_stb_o wbm_cyc_o -hier -Revised
#add_ignored_outputs wbm_cyc_o -Revised -System
# (EQ)
add_output_stuck_at 0 trace_valid -Revised -hier
add_output_stuck_at 0 {trace_data[35]} -Revised -hier
add_output_stuck_at 0 {trace_data[34]} -Revised -hier
add_output_stuck_at 0 {trace_data[33]} -Revised -hier
add_output_stuck_at 0 {trace_data[32]} -Revised -hier
add_output_stuck_at 0 {trace_data[31]} -Revised -hier
add_output_stuck_at 0 {trace_data[30]} -Revised -hier
add_output_stuck_at 0 {trace_data[29]} -Revised -hier
add_output_stuck_at 0 {trace_data[28]} -Revised -hier
add_output_stuck_at 0 {trace_data[27]} -Revised -hier
add_output_stuck_at 0 {trace_data[26]} -Revised -hier
add_output_stuck_at 0 {trace_data[25]} -Revised -hier
add_output_stuck_at 0 {trace_data[24]} -Revised -hier
add_output_stuck_at 0 {trace_data[23]} -Revised -hier
add_output_stuck_at 0 {trace_data[22]} -Revised -hier
add_output_stuck_at 0 {trace_data[21]} -Revised -hier
add_output_stuck_at 0 {trace_data[20]} -Revised -hier
add_output_stuck_at 0 {trace_data[19]} -Revised -hier
add_output_stuck_at 0 {trace_data[18]} -Revised -hier
add_output_stuck_at 0 {trace_data[17]} -Revised -hier
add_output_stuck_at 0 {trace_data[16]} -Revised -hier
add_output_stuck_at 0 {trace_data[15]} -Revised -hier
add_output_stuck_at 0 {trace_data[14]} -Revised -hier
add_output_stuck_at 0 {trace_data[13]} -Revised -hier
add_output_stuck_at 0 {trace_data[12]} -Revised -hier
add_output_stuck_at 0 {trace_data[11]} -Revised -hier
add_output_stuck_at 0 {trace_data[10]} -Revised -hier
add_output_stuck_at 0 {trace_data[9]} -Revised -hier
add_output_stuck_at 0 {trace_data[8]} -Revised -hier
add_output_stuck_at 0 {trace_data[7]} -Revised -hier
add_output_stuck_at 0 {trace_data[6]} -Revised -hier
add_output_stuck_at 0 {trace_data[5]} -Revised -hier
add_output_stuck_at 0 {trace_data[4]} -Revised -hier
add_output_stuck_at 0 {trace_data[3]} -Revised -hier
add_output_stuck_at 0 {trace_data[2]} -Revised -hier
add_output_stuck_at 0 {trace_data[1]} -Revised -hier
add_output_stuck_at 0 {trace_data[0]} -Revised -hier
report_black_box -NOHidden
set_system_mode lec
report_design_data; report_unmapped_points -summary; report_unmapped_points -notmapped; analyze_datapath -module -verbose; eval analyze_datapath -flowgraph -verbose
add_compared_points -all
compare
save_hier_compare_result
set_system_mode setup
usage
report_hier_compare_result
report_hier_compare_result -Nonequivalent
report_hier_compare_result -Abort
report_hier_compare_result -Uncompared
#-------------------------------------------------------------------------------
# VERBOSE REPORTING
#-------------------------------------------------------------------------------
# The following Golden modules are not written because of non-matching
# instance names in Revised:
# picorv32_pcpi_div (Instance: picorv32_core/genblk2.pcpi_div) (G)
# picorv32_ENABLE_COUNTERS1_ENABLE_COUNTERS641_ENABLE_REGS_16_311_ENABLE_REGS_DUALPORT1_TWO_STAGE_SHIFT1_BARREL_SHIFTER1_TWO_CYCLE_COMPARE0_TWO_CYCLE_ALU1_COMPRESSED_ISA0_CATCH_MISALIGN1_CATCH_ILLINSN1_ENABLE_PCPI1_ENABLE_MUL1_ENABLE_FAST_MUL1_ENABLE_DIV1_ENABLE_IRQ1_ENABLE_IRQ_QREGS1_ENABLE_IRQ_TIMER1_ENABLE_TRACE0_REGS_INIT_ZERO0_MASKED_IRQ0_LATCHED_IRQxffffffff_PROGADDR_RESET0_PROGADDR_IRQ16_STACKADDRxffffffff (Instance: picorv32_core) (G)
# picorv32_pcpi_fast_mul (Instance: picorv32_core/genblk1.pcpi_mul) (G)
#-------------------------------------------------------------------------------
# The following Revised modules are not written because of non-matching
# instance names in Golden:
# arith_shift_right_vlog_signed_690_rtlopto_model_90 (Instance: picorv32_core_sra_1236_80) (R)
# leq_unsigned_rtlopto_model_1638 (Instance: picorv32_core_genblk2.pcpi_div_lte_2498_16) (R)
# lt_signed_rtlopto_model_1127 (Instance: picorv32_core_lt_1233_32) (R)
# lt_unsigned_rtlopto_model_1128 (Instance: picorv32_core_lt_1234_23) (R)
# mult_signed (Instance: picorv32_core_genblk1.pcpi_mul_mul_2371_47) (R)
# shift_left_vlog_unsigned_1244 (Instance: picorv32_core_sll_1235_23) (R)
#-------------------------------------------------------------------------------
# _END_OF_LEC_HIERARCHICAL_DOFILE_
