# ==============================================================================
#  TASK 7: LOGIC EQUIVALENCE CHECK (LEC)
#  Run this in the terminal: lec -XL -nogui
#  Then copy-paste these commands.
# ==============================================================================

# ------------------------------------------------------------------------------
#  COMPARISON 1: RTL vs ELABORATED (Steps 1-2)
# ------------------------------------------------------------------------------
puts ">> STARTING COMPARISON 1: RTL vs ELABORATED"

# Load the comparison script generated by Genus
dofile rtl_vs_elab.do

# --- REPORTING FOR TASK 7 (PART A) ---
# The manual asks for "report_verification -hier -verbose" for the first comparison.
puts "\n\n========================================================"
puts "   OUTPUT FOR REPORT (RTL vs ELABORATED)"
puts "========================================================"
report_verification -hier -verbose
puts "========================================================"

# Reset the tool to prepare for the next comparison
# (If the tool exited above, relaunch and start from here)
reset -force


# ------------------------------------------------------------------------------
#  COMPARISON 2: RTL vs FINAL/SYN_OPT (Steps 3-4)
# ------------------------------------------------------------------------------
puts ">> STARTING COMPARISON 2: RTL vs FINAL NETLIST"

# Load the comparison script generated by Genus
dofile rtl_vs_final.do

# --- REPORTING FOR TASK 7 (PART B) ---
# The manual asks for "report_verification -verbose" for the final comparison.
puts "\n\n========================================================"
puts "   OUTPUT FOR REPORT (RTL vs FINAL)"
puts "========================================================"
report_verification -verbose

# The manual asks for "report_statistics" to see Equivalent Points (EQ).
puts "\n\n========================================================"
puts "   STATISTICS (Look for 'Equivalent' count)"
puts "========================================================"
report_statistics
puts "========================================================"

puts ">> LEC SEQUENCE COMPLETE."
